library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

use work.utils.all;

-- This module can be used to generate the CRC used in Ethernet, or to verify a received ethernet frame using its transmitted CRC.
-- When verifying a received packet, feed in the entire packet including the FCS, one the rising edge of the clock cycle following the last byte of the packet
-- verify_out will go high if the CRC matches.

-- This implementation uses a left shifting LFSR with post complement, init value 0xffffffff and verify value 0xC704DD7B.

entity ethernet_fcs is
  generic (
    G_USER_INIT_VAL_PORT : boolean := false
  );
  port (
    clk            : in std_logic;
    reset          : in std_logic;
    --------------------------------------------------------
    init_val_in    : in std_logic_vector(31 downto 0) := (others => '0');
    data_in        : in std_logic_vector(7 downto 0);
    valid_in       : in std_logic;
    en_calc_in     : in std_logic;
    --------------------------------------------------------
    verify_out     : out std_logic;
    fcs_byte_out   : out std_logic_vector(7 downto 0);
    crc_reg_out    : out std_logic_vector(31 downto 0)
  );
end entity ethernet_fcs;

architecture rtl of ethernet_fcs is

  ----------------------------------------------------
  -- CONSTANTS
  ----------------------------------------------------
  constant C_INIT_VAL_SLV : std_logic_vector(31 downto 0) := x"ffffffff";
  constant C_CRC_VERIFY   : std_logic_vector(31 downto 0) := x"C704DD7B";

  ----------------------------------------------------
  -- SIGNALS
  ----------------------------------------------------

  signal crc_next   : std_logic_vector(31 downto 0);

  signal crc_reg    : std_logic_vector(31 downto 0);
  signal fcs_byte   : std_logic_vector(7 downto 0);


  -- Generated by https://bues.ch/cms/hacking/crcgen
  function calc_crc32(data : std_logic_vector(7 downto 0); crc_in : std_logic_vector(31 downto 0)) return std_logic_vector is
    variable crcOut : std_logic_vector(31 downto 0);
  begin
    crcOut(0) := crc_in(24) xor crc_in(30) xor data(0) xor data(6);
    crcOut(1) := crc_in(24) xor crc_in(25) xor crc_in(30) xor crc_in(31) xor data(0) xor data(1) xor data(6) xor data(7);
    crcOut(2) := crc_in(24) xor crc_in(25) xor crc_in(26) xor crc_in(30) xor crc_in(31) xor data(0) xor data(1) xor data(2) xor data(6) xor data(7);
    crcOut(3) := crc_in(25) xor crc_in(26) xor crc_in(27) xor crc_in(31) xor data(1) xor data(2) xor data(3) xor data(7);
    crcOut(4) := crc_in(24) xor crc_in(26) xor crc_in(27) xor crc_in(28) xor crc_in(30) xor data(0) xor data(2) xor data(3) xor data(4) xor data(6);
    crcOut(5) := crc_in(24) xor crc_in(25) xor crc_in(27) xor crc_in(28) xor crc_in(29) xor crc_in(30) xor crc_in(31) xor data(0) xor data(1) xor data(3) xor data(4) xor data(5) xor data(6) xor data(7);
    crcOut(6) := crc_in(25) xor crc_in(26) xor crc_in(28) xor crc_in(29) xor crc_in(30) xor crc_in(31) xor data(1) xor data(2) xor data(4) xor data(5) xor data(6) xor data(7);
    crcOut(7) := crc_in(24) xor crc_in(26) xor crc_in(27) xor crc_in(29) xor crc_in(31) xor data(0) xor data(2) xor data(3) xor data(5) xor data(7);
    crcOut(8) := crc_in(0) xor crc_in(24) xor crc_in(25) xor crc_in(27) xor crc_in(28) xor data(0) xor data(1) xor data(3) xor data(4);
    crcOut(9) := crc_in(1) xor crc_in(25) xor crc_in(26) xor crc_in(28) xor crc_in(29) xor data(1) xor data(2) xor data(4) xor data(5);
    crcOut(10) := crc_in(2) xor crc_in(24) xor crc_in(26) xor crc_in(27) xor crc_in(29) xor data(0) xor data(2) xor data(3) xor data(5);
    crcOut(11) := crc_in(3) xor crc_in(24) xor crc_in(25) xor crc_in(27) xor crc_in(28) xor data(0) xor data(1) xor data(3) xor data(4);
    crcOut(12) := crc_in(4) xor crc_in(24) xor crc_in(25) xor crc_in(26) xor crc_in(28) xor crc_in(29) xor crc_in(30) xor data(0) xor data(1) xor data(2) xor data(4) xor data(5) xor data(6);
    crcOut(13) := crc_in(5) xor crc_in(25) xor crc_in(26) xor crc_in(27) xor crc_in(29) xor crc_in(30) xor crc_in(31) xor data(1) xor data(2) xor data(3) xor data(5) xor data(6) xor data(7);
    crcOut(14) := crc_in(6) xor crc_in(26) xor crc_in(27) xor crc_in(28) xor crc_in(30) xor crc_in(31) xor data(2) xor data(3) xor data(4) xor data(6) xor data(7);
    crcOut(15) := crc_in(7) xor crc_in(27) xor crc_in(28) xor crc_in(29) xor crc_in(31) xor data(3) xor data(4) xor data(5) xor data(7);
    crcOut(16) := crc_in(8) xor crc_in(24) xor crc_in(28) xor crc_in(29) xor data(0) xor data(4) xor data(5);
    crcOut(17) := crc_in(9) xor crc_in(25) xor crc_in(29) xor crc_in(30) xor data(1) xor data(5) xor data(6);
    crcOut(18) := crc_in(10) xor crc_in(26) xor crc_in(30) xor crc_in(31) xor data(2) xor data(6) xor data(7);
    crcOut(19) := crc_in(11) xor crc_in(27) xor crc_in(31) xor data(3) xor data(7);
    crcOut(20) := crc_in(12) xor crc_in(28) xor data(4);
    crcOut(21) := crc_in(13) xor crc_in(29) xor data(5);
    crcOut(22) := crc_in(14) xor crc_in(24) xor data(0);
    crcOut(23) := crc_in(15) xor crc_in(24) xor crc_in(25) xor crc_in(30) xor data(0) xor data(1) xor data(6);
    crcOut(24) := crc_in(16) xor crc_in(25) xor crc_in(26) xor crc_in(31) xor data(1) xor data(2) xor data(7);
    crcOut(25) := crc_in(17) xor crc_in(26) xor crc_in(27) xor data(2) xor data(3);
    crcOut(26) := crc_in(18) xor crc_in(24) xor crc_in(27) xor crc_in(28) xor crc_in(30) xor data(0) xor data(3) xor data(4) xor data(6);
    crcOut(27) := crc_in(19) xor crc_in(25) xor crc_in(28) xor crc_in(29) xor crc_in(31) xor data(1) xor data(4) xor data(5) xor data(7);
    crcOut(28) := crc_in(20) xor crc_in(26) xor crc_in(29) xor crc_in(30) xor data(2) xor data(5) xor data(6);
    crcOut(29) := crc_in(21) xor crc_in(27) xor crc_in(30) xor crc_in(31) xor data(3) xor data(6) xor data(7);
    crcOut(30) := crc_in(22) xor crc_in(28) xor crc_in(31) xor data(4) xor data(7);
    crcOut(31) := crc_in(23) xor crc_in(29) xor data(5);

    return crcOut;
  end function;
  

begin


  crc_next <= calc_crc32(reverse_slv(data_in), crc_reg);

  fcs_byte_out  <= fcs_byte;
  crc_reg_out   <= crc_reg;

  process(clk)
  begin
    if rising_edge(clk) then

      if reset = '1' then
        if G_USER_INIT_VAL_PORT = false then
          crc_reg         <= C_INIT_VAL_SLV;
        else
          crc_reg         <= init_val_in;
        end if;
      else

        if en_calc_in = '1' and valid_in = '1' then
          crc_reg   <= crc_next;
          fcs_byte  <= not reverse_slv(crc_next(31 downto 24));
        elsif valid_in = '1' then
          crc_reg   <= crc_reg(23 downto 0) & x"FF";
          fcs_byte  <= not reverse_slv(crc_reg(23 downto 16)); 
        end if;

      end if;
    end if;
  end process;

  verify_out <= '1' when crc_reg = C_CRC_VERIFY else '0';

end architecture;
